// GENERATED by scripts/gen-tour-audio.py — do not edit by hand.
// Spotlight cue timings: each entry moves the halo to `selector` when the
// step narration reaches `at` seconds. Regenerate whenever scripts change.
export interface TourCue {
  selector: string;
  at: number;
}

export const TOUR_CUES: Record<string, TourCue[]> = {
  "step-1": [
    {
      "selector": "[data-tour=\"progress\"]",
      "at": 0.0
    },
    {
      "selector": "[data-tour=\"status-breakdown\"]",
      "at": 10.76
    },
    {
      "selector": "[data-tour=\"ai-verification\"]",
      "at": 16.05
    },
    {
      "selector": "[data-tour=\"missed\"]",
      "at": 22.25
    },
    {
      "selector": "[data-tour=\"leaderboard\"]",
      "at": 26.59
    }
  ],
  "step-2": [
    {
      "selector": "[data-tour=\"visits-table\"]",
      "at": 0.0
    },
    {
      "selector": "[data-tour=\"visit-filters\"]",
      "at": 11.05
    },
    {
      "selector": "[data-tour=\"visits-table\"]",
      "at": 17.58
    }
  ],
  "step-3": [
    {
      "selector": "[data-tour=\"plan-run\"]",
      "at": 0.0
    },
    {
      "selector": "[data-tour=\"run-operators\"]",
      "at": 7.08
    },
    {
      "selector": "[data-tour=\"runs-list\"]",
      "at": 14.36
    }
  ],
  "step-4": [],
  "step-5": [
    {
      "selector": "[data-tour=\"import\"]",
      "at": 0.0
    },
    {
      "selector": "[data-tour=\"lookup\"]",
      "at": 14.99
    }
  ],
  "step-6": [
    {
      "selector": "[data-tour=\"add-operator\"]",
      "at": 0.0
    },
    {
      "selector": "[data-tour=\"staff-list\"]",
      "at": 10.59
    }
  ],
  "step-7": []
};
